#!/usr/bin/env bash
# Build the subset CN web fonts the app loads via @font-face.
#
#   assets/fonts/app-cn-base.woff2 — first-paint subset, target <= 250 KB.
#                                    Contains every CJK char that appears
#                                    literally in lib/ + ASCII / punctuation.
#   assets/fonts/app-cn-ext.woff2  — lazy-loaded extension covering the rest
#                                    of GB 2312 for runtime / user text.
#
# Both files are build artifacts: regenerated by this script and gitignored,
# in the same spirit as tool/setup-drift-web.sh. Run locally before
# `flutter run -d chrome` / `flutter build web`, and once per CI web build.
# Idempotent — re-uses cached source font and venv when nothing has changed.
#
# Usage: apps/mobile/tool/build-cn-fonts.sh
set -euo pipefail

cd "$(dirname "$0")/.."

CACHE_DIR=".dart_tool/cn_fonts"
ASSETS_DIR="assets/fonts"
VENV_DIR="$CACHE_DIR/venv"
SOURCE_DIR="$CACHE_DIR/src"
UNICODE_DIR="$CACHE_DIR/unicodes"

# Source font: Noto Sans SC variable (OFL). Pinned by SHA-256 of the file
# contents — robust to force-pushes / branch renames in google/fonts. The
# variable wght axis (100–900) is preserved through the subset, so a single
# file covers every weight the app uses (400/500/600/700) without synthetic
# bolding.
NOTO_URL="${NOTO_URL:-https://raw.githubusercontent.com/google/fonts/main/ofl/notosanssc/NotoSansSC%5Bwght%5D.ttf}"
NOTO_SHA256="${NOTO_SHA256:-a3041811a78c361b1de50f953c805e0244951c21c5bd412f7232ef0d899af0da}"
SOURCE_FONT="$SOURCE_DIR/NotoSansSC[wght].ttf"
SOURCE_STAMP="$SOURCE_DIR/.sha256"

BASE_OUT="$ASSETS_DIR/app-cn-base.woff2"
EXT_OUT="$ASSETS_DIR/app-cn-ext.woff2"
BASE_BUDGET_BYTES="${BASE_BUDGET_BYTES:-256000}"  # 250 KB target (1000-byte KB)

mkdir -p "$CACHE_DIR" "$ASSETS_DIR" "$SOURCE_DIR" "$UNICODE_DIR"

# 1. Provision a Python venv with fonttools[woff] (brotli for woff2 output).
if [ ! -x "$VENV_DIR/bin/pyftsubset" ]; then
  echo "creating fonttools venv at $VENV_DIR"
  python3 -m venv "$VENV_DIR"
  "$VENV_DIR/bin/pip" install --quiet --upgrade pip
  "$VENV_DIR/bin/pip" install --quiet 'fonttools[woff]>=4.50,<5'
fi
PYFTSUBSET="$VENV_DIR/bin/pyftsubset"
PYTHON="$VENV_DIR/bin/python"

# 2. Fetch the source font and verify its SHA-256. Re-fetches when the
#    cached stamp is missing, has been tampered with, or doesn't match
#    the pinned hash.
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

current_sha=""
if [ -f "$SOURCE_FONT" ]; then
  current_sha=$(sha256_of "$SOURCE_FONT")
fi
if [ "$current_sha" != "$NOTO_SHA256" ]; then
  echo "fetching Noto Sans SC variable from $NOTO_URL"
  curl --fail --silent --show-error --location --output "$SOURCE_FONT" "$NOTO_URL"
  current_sha=$(sha256_of "$SOURCE_FONT")
  if [ "$current_sha" != "$NOTO_SHA256" ]; then
    echo "::error::source font sha256 mismatch" >&2
    echo "  expected: $NOTO_SHA256" >&2
    echo "  got:      $current_sha" >&2
    echo "  Upstream changed; verify the new file then update NOTO_SHA256 in this script." >&2
    exit 1
  fi
  echo "$NOTO_SHA256" > "$SOURCE_STAMP"
else
  echo "source font already cached (sha256 $NOTO_SHA256)"
fi

# 3. Build the unicode lists from the live codebase.
BASE_UNICODES="$UNICODE_DIR/base.txt"
EXT_UNICODES="$UNICODE_DIR/ext.txt"
"$PYTHON" tool/cn_font_chars.py \
  --lib-root lib \
  --out-base "$BASE_UNICODES" \
  --out-ext "$EXT_UNICODES"

# 4. Subset the source font into base + ext woff2 outputs.
#    --layout-features=*  keeps GSUB/GPOS so tabular figures + locale forms work.
#    --no-hinting drops PostScript hinting (Noto Sans SC ships without it
#    anyway; flag is explicit so the output is deterministic).
common_args=(
  --flavor=woff2
  --with-zopfli
  --layout-features='*'
  --glyph-names
  --symbol-cmap
  --legacy-cmap
  --notdef-glyph
  --notdef-outline
  --recommended-glyphs
  --name-legacy
  --drop-tables+=DSIG
  --no-hinting
)

echo "subsetting → $BASE_OUT"
"$PYFTSUBSET" "$SOURCE_FONT" \
  --unicodes-file="$BASE_UNICODES" \
  --output-file="$BASE_OUT" \
  "${common_args[@]}"

echo "subsetting → $EXT_OUT"
"$PYFTSUBSET" "$SOURCE_FONT" \
  --unicodes-file="$EXT_UNICODES" \
  --output-file="$EXT_OUT" \
  "${common_args[@]}"

# 5. Enforce the first-paint size budget. Better to fail the build than to
#    quietly ship a 4 MB CJK font on the first request.
base_size=$(wc -c < "$BASE_OUT" | tr -d ' ')
ext_size=$(wc -c < "$EXT_OUT" | tr -d ' ')
echo "produced $BASE_OUT ($base_size bytes), $EXT_OUT ($ext_size bytes)"
if [ "$base_size" -gt "$BASE_BUDGET_BYTES" ]; then
  echo "::error::$BASE_OUT is $base_size bytes, exceeds budget $BASE_BUDGET_BYTES (250 KB)" >&2
  echo "  Trim ALWAYS_INCLUDE in tool/cn_font_chars.py, or move chars to the ext tier." >&2
  exit 1
fi
echo "ok — base subset within 250 KB budget"
