import 'dart:convert';

import 'package:decimal/decimal.dart';

/// Structured, model-agnostic explanation of why a scored opportunity is
/// good / risky / a fit. Generated by the scorer (`docs/options-income.md`
/// §7.3) and read verbatim by both the UI cards and the AI tool.
///
/// LLMs **do not rewrite** these fields — they can only reference and
/// paraphrase them. That guarantees UI and chat see the same story.
class OpportunityExplanation {
  const OpportunityExplanation({
    required this.summary,
    required this.whyGood,
    required this.whyRisky,
    required this.bestFor,
    required this.avoidIf,
    required this.worstCase,
    required this.scoreBreakdown,
  });

  /// One-line headline, e.g. "AAPL 30-day put @ $190 — 14% annualized,
  /// 12% margin of safety."
  final String summary;

  /// Up to 3 bullets pulled from the top score dimensions.
  final List<String> whyGood;

  /// Up to 3 bullets pulled from weak dimensions / near-edge hard
  /// filters.
  final List<String> whyRisky;

  /// Profile-mode-tuned one-liner ("适合保守现金流偏好").
  final String bestFor;

  /// One-liner stating when the user should pass.
  final String avoidIf;

  /// Plain-language worst-case scenario — covered by `docs/options-income.md`
  /// §11.1 ("If `{symbol}` falls below $\{strike\}, you will buy 100
  /// shares at $\{breakeven\} ...").
  final String worstCase;

  /// `{yield: 0.84, liquidity: 0.71, ...}`. Keys mirror the scorer's
  /// soft-score dimensions.
  final Map<String, Decimal> scoreBreakdown;

  Map<String, Object?> toJson() => <String, Object?>{
    'summary': summary,
    'why_good': whyGood,
    'why_risky': whyRisky,
    'best_for': bestFor,
    'avoid_if': avoidIf,
    'worst_case': worstCase,
    'score_breakdown': {
      for (final entry in scoreBreakdown.entries)
        entry.key: entry.value.toString(),
    },
  };

  String encode() => jsonEncode(toJson());

  static OpportunityExplanation decode(String raw) {
    final json = jsonDecode(raw);
    if (json is! Map<String, Object?>) {
      throw const FormatException('OpportunityExplanation: not a JSON object');
    }
    return OpportunityExplanation.fromJson(json);
  }

  factory OpportunityExplanation.fromJson(Map<String, Object?> json) {
    final breakdownRaw = json['score_breakdown'];
    final breakdown = <String, Decimal>{};
    if (breakdownRaw is Map) {
      breakdownRaw.forEach((key, value) {
        if (key is String && value is String) {
          breakdown[key] = Decimal.parse(value);
        }
      });
    }
    return OpportunityExplanation(
      summary: (json['summary'] as String?) ?? '',
      whyGood:
          (json['why_good'] as List?)?.whereType<String>().toList() ?? const [],
      whyRisky:
          (json['why_risky'] as List?)?.whereType<String>().toList() ??
          const [],
      bestFor: (json['best_for'] as String?) ?? '',
      avoidIf: (json['avoid_if'] as String?) ?? '',
      worstCase: (json['worst_case'] as String?) ?? '',
      scoreBreakdown: breakdown,
    );
  }
}
