// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/agent_runtime.dart';
import 'api/embedder.dart';
import 'api/health.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0-beta.6';

  @override
  int get rustContentHash => 1562559713;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'lifeos_native',
        ioDirectory: 'native/lifeos_native/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  int crateApiEmbedderGemmaEmbedderDimension({required GemmaEmbedder that});

  Future<Float32List> crateApiEmbedderGemmaEmbedderEmbed({
    required GemmaEmbedder that,
    required String text,
  });

  String crateApiEmbedderGemmaEmbedderFingerprint({
    required GemmaEmbedder that,
  });

  Future<GemmaEmbedder> crateApiEmbedderGemmaEmbedderLoad({
    required String modelDir,
    required String ortDylibPath,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeCancelRunSnapshot({
    required String catalogJson,
    required String snapshotJson,
    required String agentId,
    required String reason,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeCatalogSummary({
    required String catalogJson,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeCatalogVersion();

  Future<String> crateApiAgentRuntimeAgentRuntimeCompleteMockLlm({
    required String requestJson,
    required String responseText,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeCompleteProfileLlm({
    required String requestJson,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeContinueRunSnapshot({
    required String catalogJson,
    required String snapshotJson,
    required String effectResponseJson,
    required String agentId,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeProtocolVersion();

  Future<String>
  crateApiAgentRuntimeAgentRuntimeResumeParentFromSubagentSnapshot({
    required String catalogJson,
    required String parentSnapshotJson,
    required String childSnapshotJson,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeStartProfileTurnSnapshot({
    required String catalogJson,
    required String llmRequestJson,
    required String agentId,
    required String runMetadataJson,
    required int maxEffectSteps,
    required int maxSubagentDepth,
  });

  Future<String>
  crateApiAgentRuntimeAgentRuntimeStartRequestedSubagentSnapshot({
    required String catalogJson,
    required String parentSnapshotJson,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeStartRunSnapshot({
    required String catalogJson,
    required String requestJson,
    required String agentId,
    required int maxEffectSteps,
    required int maxSubagentDepth,
  });

  Stream<String> crateApiAgentRuntimeAgentRuntimeStreamChatTurn({
    required String requestJson,
  });

  Stream<String> crateApiAgentRuntimeAgentRuntimeStreamMockLlm({
    required String requestJson,
    required String responseText,
  });

  Stream<String> crateApiAgentRuntimeAgentRuntimeStreamProfileLlm({
    required String requestJson,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeValidateChatTurnRequest({
    required String requestJson,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeValidateLlmRequest({
    required String requestJson,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeValidateLlmResponse({
    required String responseJson,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeValidateRunRequest({
    required String requestJson,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeValidateToolSpec({
    required String toolJson,
  });

  Future<String> crateApiAgentRuntimeAgentRuntimeValidateTrace({
    required String traceJson,
  });

  String crateApiEmbedderEmbedderFingerprint();

  int crateApiEmbedderEmbeddingDim();

  Future<String> crateApiHealthGarminAuthState();

  Future<String> crateApiHealthGarminAuthenticate({
    required String email,
    required String password,
  });

  Future<String?> crateApiHealthGarminExportSession();

  Future<String> crateApiHealthGarminInit({
    String? storedTokenJson,
    required bool isCn,
  });

  Future<void> crateApiHealthGarminLogout();

  Future<String> crateApiHealthGarminSubmitMfa({required String code});

  Future<void> crateApiHealthGarminSyncCancel();

  Future<String> crateApiHealthGarminSyncCursors();

  Future<String> crateApiHealthGarminSyncRange({
    required String from,
    required String to,
  });

  Stream<GarminSyncProgress> crateApiHealthGarminSyncRangeStream({
    required String from,
    required String to,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GemmaEmbedder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GemmaEmbedder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_GemmaEmbedderPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  int crateApiEmbedderGemmaEmbedderDimension({required GemmaEmbedder that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEmbedderGemmaEmbedderDimensionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedderGemmaEmbedderDimensionConstMeta =>
      const TaskConstMeta(
        debugName: "GemmaEmbedder_dimension",
        argNames: ["that"],
      );

  @override
  Future<Float32List> crateApiEmbedderGemmaEmbedderEmbed({
    required GemmaEmbedder that,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
            that,
            serializer,
          );
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEmbedderGemmaEmbedderEmbedConstMeta,
        argValues: [that, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedderGemmaEmbedderEmbedConstMeta =>
      const TaskConstMeta(
        debugName: "GemmaEmbedder_embed",
        argNames: ["that", "text"],
      );

  @override
  String crateApiEmbedderGemmaEmbedderFingerprint({
    required GemmaEmbedder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEmbedderGemmaEmbedderFingerprintConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedderGemmaEmbedderFingerprintConstMeta =>
      const TaskConstMeta(
        debugName: "GemmaEmbedder_fingerprint",
        argNames: ["that"],
      );

  @override
  Future<GemmaEmbedder> crateApiEmbedderGemmaEmbedderLoad({
    required String modelDir,
    required String ortDylibPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelDir, serializer);
          sse_encode_String(ortDylibPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEmbedderGemmaEmbedderLoadConstMeta,
        argValues: [modelDir, ortDylibPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedderGemmaEmbedderLoadConstMeta =>
      const TaskConstMeta(
        debugName: "GemmaEmbedder_load",
        argNames: ["modelDir", "ortDylibPath"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeCancelRunSnapshot({
    required String catalogJson,
    required String snapshotJson,
    required String agentId,
    required String reason,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(catalogJson, serializer);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_String(agentId, serializer);
          sse_encode_String(reason, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeCancelRunSnapshotConstMeta,
        argValues: [catalogJson, snapshotJson, agentId, reason],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeCancelRunSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_cancel_run_snapshot",
        argNames: ["catalogJson", "snapshotJson", "agentId", "reason"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeCatalogSummary({
    required String catalogJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(catalogJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeCatalogSummaryConstMeta,
        argValues: [catalogJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentRuntimeAgentRuntimeCatalogSummaryConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_catalog_summary",
        argNames: ["catalogJson"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeCatalogVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeCatalogVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentRuntimeAgentRuntimeCatalogVersionConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_catalog_version",
        argNames: [],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeCompleteMockLlm({
    required String requestJson,
    required String responseText,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(requestJson, serializer);
          sse_encode_String(responseText, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeCompleteMockLlmConstMeta,
        argValues: [requestJson, responseText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentRuntimeAgentRuntimeCompleteMockLlmConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_complete_mock_llm",
        argNames: ["requestJson", "responseText"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeCompleteProfileLlm({
    required String requestJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(requestJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeCompleteProfileLlmConstMeta,
        argValues: [requestJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeCompleteProfileLlmConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_complete_profile_llm",
        argNames: ["requestJson"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeContinueRunSnapshot({
    required String catalogJson,
    required String snapshotJson,
    required String effectResponseJson,
    required String agentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(catalogJson, serializer);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_String(effectResponseJson, serializer);
          sse_encode_String(agentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiAgentRuntimeAgentRuntimeContinueRunSnapshotConstMeta,
        argValues: [catalogJson, snapshotJson, effectResponseJson, agentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeContinueRunSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_continue_run_snapshot",
        argNames: [
          "catalogJson",
          "snapshotJson",
          "effectResponseJson",
          "agentId",
        ],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeProtocolVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeProtocolVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentRuntimeAgentRuntimeProtocolVersionConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_protocol_version",
        argNames: [],
      );

  @override
  Future<String>
  crateApiAgentRuntimeAgentRuntimeResumeParentFromSubagentSnapshot({
    required String catalogJson,
    required String parentSnapshotJson,
    required String childSnapshotJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(catalogJson, serializer);
          sse_encode_String(parentSnapshotJson, serializer);
          sse_encode_String(childSnapshotJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiAgentRuntimeAgentRuntimeResumeParentFromSubagentSnapshotConstMeta,
        argValues: [catalogJson, parentSnapshotJson, childSnapshotJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeResumeParentFromSubagentSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_resume_parent_from_subagent_snapshot",
        argNames: ["catalogJson", "parentSnapshotJson", "childSnapshotJson"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeStartProfileTurnSnapshot({
    required String catalogJson,
    required String llmRequestJson,
    required String agentId,
    required String runMetadataJson,
    required int maxEffectSteps,
    required int maxSubagentDepth,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(catalogJson, serializer);
          sse_encode_String(llmRequestJson, serializer);
          sse_encode_String(agentId, serializer);
          sse_encode_String(runMetadataJson, serializer);
          sse_encode_u_32(maxEffectSteps, serializer);
          sse_encode_u_32(maxSubagentDepth, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiAgentRuntimeAgentRuntimeStartProfileTurnSnapshotConstMeta,
        argValues: [
          catalogJson,
          llmRequestJson,
          agentId,
          runMetadataJson,
          maxEffectSteps,
          maxSubagentDepth,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeStartProfileTurnSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_start_profile_turn_snapshot",
        argNames: [
          "catalogJson",
          "llmRequestJson",
          "agentId",
          "runMetadataJson",
          "maxEffectSteps",
          "maxSubagentDepth",
        ],
      );

  @override
  Future<String>
  crateApiAgentRuntimeAgentRuntimeStartRequestedSubagentSnapshot({
    required String catalogJson,
    required String parentSnapshotJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(catalogJson, serializer);
          sse_encode_String(parentSnapshotJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiAgentRuntimeAgentRuntimeStartRequestedSubagentSnapshotConstMeta,
        argValues: [catalogJson, parentSnapshotJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeStartRequestedSubagentSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_start_requested_subagent_snapshot",
        argNames: ["catalogJson", "parentSnapshotJson"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeStartRunSnapshot({
    required String catalogJson,
    required String requestJson,
    required String agentId,
    required int maxEffectSteps,
    required int maxSubagentDepth,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(catalogJson, serializer);
          sse_encode_String(requestJson, serializer);
          sse_encode_String(agentId, serializer);
          sse_encode_u_32(maxEffectSteps, serializer);
          sse_encode_u_32(maxSubagentDepth, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeStartRunSnapshotConstMeta,
        argValues: [
          catalogJson,
          requestJson,
          agentId,
          maxEffectSteps,
          maxSubagentDepth,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeStartRunSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_start_run_snapshot",
        argNames: [
          "catalogJson",
          "requestJson",
          "agentId",
          "maxEffectSteps",
          "maxSubagentDepth",
        ],
      );

  @override
  Stream<String> crateApiAgentRuntimeAgentRuntimeStreamChatTurn({
    required String requestJson,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            sse_encode_String(requestJson, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 16,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiAgentRuntimeAgentRuntimeStreamChatTurnConstMeta,
          argValues: [sink, requestJson],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAgentRuntimeAgentRuntimeStreamChatTurnConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_stream_chat_turn",
        argNames: ["sink", "requestJson"],
      );

  @override
  Stream<String> crateApiAgentRuntimeAgentRuntimeStreamMockLlm({
    required String requestJson,
    required String responseText,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            sse_encode_String(requestJson, serializer);
            sse_encode_String(responseText, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 17,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiAgentRuntimeAgentRuntimeStreamMockLlmConstMeta,
          argValues: [sink, requestJson, responseText],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAgentRuntimeAgentRuntimeStreamMockLlmConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_stream_mock_llm",
        argNames: ["sink", "requestJson", "responseText"],
      );

  @override
  Stream<String> crateApiAgentRuntimeAgentRuntimeStreamProfileLlm({
    required String requestJson,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            sse_encode_String(requestJson, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 18,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiAgentRuntimeAgentRuntimeStreamProfileLlmConstMeta,
          argValues: [sink, requestJson],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeStreamProfileLlmConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_stream_profile_llm",
        argNames: ["sink", "requestJson"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeValidateChatTurnRequest({
    required String requestJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(requestJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiAgentRuntimeAgentRuntimeValidateChatTurnRequestConstMeta,
        argValues: [requestJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeValidateChatTurnRequestConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_validate_chat_turn_request",
        argNames: ["requestJson"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeValidateLlmRequest({
    required String requestJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(requestJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeValidateLlmRequestConstMeta,
        argValues: [requestJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeValidateLlmRequestConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_validate_llm_request",
        argNames: ["requestJson"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeValidateLlmResponse({
    required String responseJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(responseJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiAgentRuntimeAgentRuntimeValidateLlmResponseConstMeta,
        argValues: [responseJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeValidateLlmResponseConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_validate_llm_response",
        argNames: ["responseJson"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeValidateRunRequest({
    required String requestJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(requestJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeValidateRunRequestConstMeta,
        argValues: [requestJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeValidateRunRequestConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_validate_run_request",
        argNames: ["requestJson"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeValidateToolSpec({
    required String toolJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(toolJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeValidateToolSpecConstMeta,
        argValues: [toolJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAgentRuntimeAgentRuntimeValidateToolSpecConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_validate_tool_spec",
        argNames: ["toolJson"],
      );

  @override
  Future<String> crateApiAgentRuntimeAgentRuntimeValidateTrace({
    required String traceJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(traceJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAgentRuntimeAgentRuntimeValidateTraceConstMeta,
        argValues: [traceJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentRuntimeAgentRuntimeValidateTraceConstMeta =>
      const TaskConstMeta(
        debugName: "agent_runtime_validate_trace",
        argNames: ["traceJson"],
      );

  @override
  String crateApiEmbedderEmbedderFingerprint() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEmbedderEmbedderFingerprintConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedderEmbedderFingerprintConstMeta =>
      const TaskConstMeta(debugName: "embedder_fingerprint", argNames: []);

  @override
  int crateApiEmbedderEmbeddingDim() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEmbedderEmbeddingDimConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedderEmbeddingDimConstMeta =>
      const TaskConstMeta(debugName: "embedding_dim", argNames: []);

  @override
  Future<String> crateApiHealthGarminAuthState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHealthGarminAuthStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthGarminAuthStateConstMeta =>
      const TaskConstMeta(debugName: "garmin_auth_state", argNames: []);

  @override
  Future<String> crateApiHealthGarminAuthenticate({
    required String email,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(email, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHealthGarminAuthenticateConstMeta,
        argValues: [email, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthGarminAuthenticateConstMeta =>
      const TaskConstMeta(
        debugName: "garmin_authenticate",
        argNames: ["email", "password"],
      );

  @override
  Future<String?> crateApiHealthGarminExportSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHealthGarminExportSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthGarminExportSessionConstMeta =>
      const TaskConstMeta(debugName: "garmin_export_session", argNames: []);

  @override
  Future<String> crateApiHealthGarminInit({
    String? storedTokenJson,
    required bool isCn,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(storedTokenJson, serializer);
          sse_encode_bool(isCn, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHealthGarminInitConstMeta,
        argValues: [storedTokenJson, isCn],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthGarminInitConstMeta => const TaskConstMeta(
    debugName: "garmin_init",
    argNames: ["storedTokenJson", "isCn"],
  );

  @override
  Future<void> crateApiHealthGarminLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHealthGarminLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthGarminLogoutConstMeta =>
      const TaskConstMeta(debugName: "garmin_logout", argNames: []);

  @override
  Future<String> crateApiHealthGarminSubmitMfa({required String code}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHealthGarminSubmitMfaConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthGarminSubmitMfaConstMeta =>
      const TaskConstMeta(debugName: "garmin_submit_mfa", argNames: ["code"]);

  @override
  Future<void> crateApiHealthGarminSyncCancel() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHealthGarminSyncCancelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthGarminSyncCancelConstMeta =>
      const TaskConstMeta(debugName: "garmin_sync_cancel", argNames: []);

  @override
  Future<String> crateApiHealthGarminSyncCursors() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHealthGarminSyncCursorsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthGarminSyncCursorsConstMeta =>
      const TaskConstMeta(debugName: "garmin_sync_cursors", argNames: []);

  @override
  Future<String> crateApiHealthGarminSyncRange({
    required String from,
    required String to,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(from, serializer);
          sse_encode_String(to, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHealthGarminSyncRangeConstMeta,
        argValues: [from, to],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthGarminSyncRangeConstMeta =>
      const TaskConstMeta(
        debugName: "garmin_sync_range",
        argNames: ["from", "to"],
      );

  @override
  Stream<GarminSyncProgress> crateApiHealthGarminSyncRangeStream({
    required String from,
    required String to,
  }) {
    final sink = RustStreamSink<GarminSyncProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_garmin_sync_progress_Sse(sink, serializer);
            sse_encode_String(from, serializer);
            sse_encode_String(to, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 36,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiHealthGarminSyncRangeStreamConstMeta,
          argValues: [sink, from, to],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiHealthGarminSyncRangeStreamConstMeta =>
      const TaskConstMeta(
        debugName: "garmin_sync_range_stream",
        argNames: ["sink", "from", "to"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GemmaEmbedder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GemmaEmbedder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  GemmaEmbedder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GemmaEmbedder
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GemmaEmbedder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<GarminSyncProgress>
  dco_decode_StreamSink_garmin_sync_progress_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GarminSyncProgress dco_decode_garmin_sync_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return GarminSyncProgress(
      phase: dco_decode_String(arr[0]),
      current: dco_decode_i_32(arr[1]),
      total: dco_decode_i_32(arr[2]),
      metricsCount: dco_decode_i_32(arr[3]),
      errors: dco_decode_list_String(arr[4]),
      snapshotJson: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  GemmaEmbedder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GemmaEmbedder
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GemmaEmbedder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<GarminSyncProgress>
  sse_decode_StreamSink_garmin_sync_progress_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  GarminSyncProgress sse_decode_garmin_sync_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_String(deserializer);
    var var_current = sse_decode_i_32(deserializer);
    var var_total = sse_decode_i_32(deserializer);
    var var_metricsCount = sse_decode_i_32(deserializer);
    var var_errors = sse_decode_list_String(deserializer);
    var var_snapshotJson = sse_decode_opt_String(deserializer);
    return GarminSyncProgress(
      phase: var_phase,
      current: var_current,
      total: var_total,
      metricsCount: var_metricsCount,
      errors: var_errors,
      snapshotJson: var_snapshotJson,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    GemmaEmbedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GemmaEmbedderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    GemmaEmbedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GemmaEmbedderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    GemmaEmbedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GemmaEmbedderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_garmin_sync_progress_Sse(
    RustStreamSink<GarminSyncProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_garmin_sync_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_garmin_sync_progress(
    GarminSyncProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.phase, serializer);
    sse_encode_i_32(self.current, serializer);
    sse_encode_i_32(self.total, serializer);
    sse_encode_i_32(self.metricsCount, serializer);
    sse_encode_list_String(self.errors, serializer);
    sse_encode_opt_String(self.snapshotJson, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class GemmaEmbedderImpl extends RustOpaque implements GemmaEmbedder {
  // Not to be used by end users
  GemmaEmbedderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  GemmaEmbedderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_GemmaEmbedder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_GemmaEmbedder,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_GemmaEmbedderPtr,
  );

  /// Output dimension. Always 768 for EmbeddingGemma-300M; the
  /// `#[frb(sync)]` hint makes this a plain `int` getter on Dart.
  int dimension() =>
      RustLib.instance.api.crateApiEmbedderGemmaEmbedderDimension(that: this);

  /// Embed `text` into a unit-length 768-d vector. fastembed
  /// L2-normalises by default; we sanity-check the dimension to
  /// catch model/config mismatches early.
  Future<Float32List> embed({required String text}) => RustLib.instance.api
      .crateApiEmbedderGemmaEmbedderEmbed(that: this, text: text);

  /// Stable identifier. The Memory Layer persists this with every
  /// embedding so swapping models invalidates the vectors.
  String fingerprint() =>
      RustLib.instance.api.crateApiEmbedderGemmaEmbedderFingerprint(that: this);
}
