//! `lifeos_native` — native primitives for the Flutter app.
//!
//! Bindings to Dart are auto-generated by `flutter_rust_bridge_codegen`
//! (D-1.7c per `docs/lifeos-shell.md` §6.6). The only thing the
//! generator scans is `crate::api`; everything else is private
//! implementation. `frb_generated` is produced by the codegen at
//! `tool/build-lifeos-native.sh` / on-demand `flutter_rust_bridge_codegen generate`.

pub mod api;

#[allow(clippy::all)]
#[allow(dead_code)]
#[allow(unused_imports)]
#[allow(unused_variables)]
#[allow(non_snake_case)]
mod frb_generated;
