//! `lifeos_native` — native primitives for the Flutter app.
//!
//! Bindings to Dart are auto-generated by `flutter_rust_bridge_codegen`
//! (D-1.7c per `docs/architecture/lifeos-shell.md` §6.6). The only thing the
//! generator scans is `crate::api`; everything else is private
//! implementation. `frb_generated` is produced by the codegen at
//! on demand by `flutter_rust_bridge_codegen generate`.

pub mod api;

pub(crate) mod android_tls;

// Internal agent runtime implementation — outside `api/` so FRB codegen sees
// only the primitive wrapper in `api/agent_runtime.rs`.
pub(crate) mod agent_runtime;

// Internal health implementation — outside `api/` so FRB codegen
// doesn't scan it. The thin FRB surface is at `api/health.rs`.
pub(crate) mod health;

#[allow(clippy::all)]
#[allow(dead_code)]
#[allow(unused_imports)]
#[allow(unused_variables)]
#[allow(non_snake_case)]
mod frb_generated;
