#!/usr/bin/env bash
# Keep the Dart runtime package, Rust crate, lockfile, and generated bindings
# on one flutter_rust_bridge version. A mismatch only surfaces at native
# runtime initialization, so fail it during the static quality gate instead.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
mobile_root="$repo_root/apps/mobile"
cargo_root="$mobile_root/native/lifeos_native"

dart_runtime_version="$(
  awk '$1 == "flutter_rust_bridge:" { print $2; exit }' \
    "$mobile_root/pubspec.yaml" \
    | tr -d "'\""
)"
rust_runtime_version="$(
  sed -nE 's/^[[:space:]]*flutter_rust_bridge[[:space:]]*=[[:space:]]*"=([^"]+)".*/\1/p' \
    "$cargo_root/Cargo.toml"
)"
dart_codegen_version="$(
  sed -nE "s/.*codegenVersion => '([^']+)'.*/\1/p" \
    "$mobile_root/lib/src/rust/frb_generated.dart"
)"
rust_codegen_version="$(
  sed -nE 's/.*FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "([^"]+)".*/\1/p' \
    "$cargo_root/src/frb_generated.rs"
)"
dart_content_hash="$(
  sed -nE 's/.*rustContentHash => ([0-9-]+).*/\1/p' \
    "$mobile_root/lib/src/rust/frb_generated.dart"
)"
rust_content_hash="$(
  sed -nE 's/.*FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = ([0-9-]+).*/\1/p' \
    "$cargo_root/src/frb_generated.rs"
)"

failed=false

check_equal() {
  local label="$1"
  local actual="$2"
  local expected="$3"
  if [[ -z "$actual" || "$actual" != "$expected" ]]; then
    echo "✖ $label is '${actual:-missing}', expected '$expected'." >&2
    failed=true
  fi
}

if [[ -z "$dart_runtime_version" ]]; then
  echo "✖ flutter_rust_bridge is missing from apps/mobile/pubspec.yaml." >&2
  exit 1
fi

check_equal "Rust flutter_rust_bridge dependency" \
  "$rust_runtime_version" "$dart_runtime_version"
check_equal "generated Dart FRB version" \
  "$dart_codegen_version" "$dart_runtime_version"
check_equal "generated Rust FRB version" \
  "$rust_codegen_version" "$dart_runtime_version"
check_equal "generated Rust FRB content hash" \
  "$rust_content_hash" "$dart_content_hash"

lock_count=0
while IFS= read -r lock_version; do
  lock_count=$((lock_count + 1))
  check_equal "Cargo.lock FRB package #$lock_count" \
    "$lock_version" "$dart_runtime_version"
done < <(
  awk '
    /^name = "flutter_rust_bridge(_macros)?"$/ { read_version = 1; next }
    read_version && /^version = / {
      gsub(/^version = "|"$/, "")
      print
      read_version = 0
    }
  ' "$cargo_root/Cargo.lock"
)

if [[ "$lock_count" -ne 2 ]]; then
  echo "✖ expected flutter_rust_bridge and flutter_rust_bridge_macros in Cargo.lock; found $lock_count." >&2
  failed=true
fi

generated_files=(
  "$mobile_root/lib/src/rust/api/agent_runtime.dart"
  "$mobile_root/lib/src/rust/api/embedder.dart"
  "$mobile_root/lib/src/rust/api/health.dart"
  "$mobile_root/lib/src/rust/frb_generated.dart"
  "$mobile_root/lib/src/rust/frb_generated.io.dart"
  "$mobile_root/lib/src/rust/frb_generated.web.dart"
  "$cargo_root/src/frb_generated.rs"
)

for generated_file in "${generated_files[@]}"; do
  header_version="$(
    sed -nE 's/^\/\/ @generated by `flutter_rust_bridge`@ ([^.]+(\.[^.]+)*).$/\1/p' \
      "$generated_file" \
      | head -n 1
  )"
  check_equal "generated header ${generated_file#"$repo_root/"}" \
    "$header_version" "$dart_runtime_version"
done

if [[ "$failed" == true ]]; then
  echo >&2
  echo "Run flutter_rust_bridge_codegen at the same version as pubspec.yaml" >&2
  echo "after aligning native/lifeos_native/Cargo.toml, then commit all" >&2
  echo "generated Dart/Rust bindings and Cargo.lock changes." >&2
  exit 1
fi

echo "✓ flutter_rust_bridge runtime and generated bindings align at $dart_runtime_version."
