// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'auth.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

@freezed
sealed class AuthResult with _$AuthResult {
  const AuthResult._();

  /// Successfully authenticated.
  const factory AuthResult.authenticated() = AuthResult_Authenticated;

  /// MFA code required — caller should prompt the user.
  const factory AuthResult.mfaRequired() = AuthResult_MfaRequired;

  /// Authentication failed.
  const factory AuthResult.failed(String field0) = AuthResult_Failed;
}

@freezed
sealed class GarminAuthState with _$GarminAuthState {
  const GarminAuthState._();

  /// No credentials stored.
  const factory GarminAuthState.unauthenticated() =
      GarminAuthState_Unauthenticated;

  /// SSO returned an MFA challenge.
  const factory GarminAuthState.pendingMfa({
    /// Opaque session ticket from the SSO flow.
    required String sessionTicket,
  }) = GarminAuthState_PendingMfa;

  /// Authenticated and token is valid.
  const factory GarminAuthState.authenticated({required DateTime expiresAt}) =
      GarminAuthState_Authenticated;

  /// Token expired, refresh in progress.
  const factory GarminAuthState.refreshing() = GarminAuthState_Refreshing;

  /// Terminal error (wrong credentials, account locked, etc.).
  const factory GarminAuthState.error({required String message}) =
      GarminAuthState_Error;

  /// Whether the client can make API calls in this state.
  Future<bool> canMakeRequests() => RustLib.instance.api
      .crateApiHealthGarminAuthGarminAuthStateCanMakeRequests(that: this);

  /// Whether the token needs refreshing.
  Future<bool> needsRefresh() => RustLib.instance.api
      .crateApiHealthGarminAuthGarminAuthStateNeedsRefresh(that: this);
}
