// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../../lib.dart';
import 'auth.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `sso_mfa_url`, `sso_signin_url`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GarminClient>>
abstract class GarminClient implements RustOpaqueInterface {
  /// Get current auth state.
  Future<GarminAuthState> authState();

  /// Authenticate with email/password via Garmin SSO.
  Future<AuthResult> authenticate({
    required String email,
    required String password,
  });

  /// Get the underlying HTTP client (for endpoint calls).
  Future<void> http();

  /// Check if authenticated.
  Future<bool> isAuthenticated();

  /// Whether this client uses the China region.
  Future<bool> isCn();

  /// Logout and clear stored credentials.
  Future<void> logout();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new client. Attempts to load stored credentials.
  static Future<GarminClient> newInstance({
    required ArcTokenStore tokenStore,
    required bool isCn,
  }) => RustLib.instance.api.crateApiHealthGarminClientGarminClientNew(
    tokenStore: tokenStore,
    isCn: isCn,
  );

  /// Get the rate limiter (for endpoint calls).
  Future<void> rateLimiter();

  /// Refresh the session token.
  Future<void> refreshToken();

  /// Submit MFA code.
  Future<AuthResult> submitMfa({required String code});
}
