// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rate_limiter.dart';

// These functions are ignored because they are not marked as `pub`: `base_url`, `get_json`

/// Fetch daily summary for a single date.
Future<Value> fetchDailySummary({
  required Client client,
  required GarminRateLimiter rateLimiter,
  required NaiveDate date,
  required bool isCn,
}) => RustLib.instance.api.crateApiHealthGarminEndpointsFetchDailySummary(
  client: client,
  rateLimiter: rateLimiter,
  date: date,
  isCn: isCn,
);

/// Fetch steps data for a date range.
Future<Value> fetchSteps({
  required Client client,
  required GarminRateLimiter rateLimiter,
  required NaiveDate from,
  required NaiveDate to,
  required bool isCn,
}) => RustLib.instance.api.crateApiHealthGarminEndpointsFetchSteps(
  client: client,
  rateLimiter: rateLimiter,
  from: from,
  to: to,
  isCn: isCn,
);

/// Fetch sleep data for a date.
Future<Value> fetchSleep({
  required Client client,
  required GarminRateLimiter rateLimiter,
  required NaiveDate date,
  required bool isCn,
}) => RustLib.instance.api.crateApiHealthGarminEndpointsFetchSleep(
  client: client,
  rateLimiter: rateLimiter,
  date: date,
  isCn: isCn,
);

/// Fetch resting heart rate for a date range.
Future<Value> fetchRhr({
  required Client client,
  required GarminRateLimiter rateLimiter,
  required NaiveDate from,
  required NaiveDate to,
  required bool isCn,
}) => RustLib.instance.api.crateApiHealthGarminEndpointsFetchRhr(
  client: client,
  rateLimiter: rateLimiter,
  from: from,
  to: to,
  isCn: isCn,
);

/// Fetch HRV data for a date.
Future<Value> fetchHrv({
  required Client client,
  required GarminRateLimiter rateLimiter,
  required NaiveDate date,
  required bool isCn,
}) => RustLib.instance.api.crateApiHealthGarminEndpointsFetchHrv(
  client: client,
  rateLimiter: rateLimiter,
  date: date,
  isCn: isCn,
);

/// Fetch Body Battery data for a date range.
Future<Value> fetchBodyBattery({
  required Client client,
  required GarminRateLimiter rateLimiter,
  required NaiveDate from,
  required NaiveDate to,
  required bool isCn,
}) => RustLib.instance.api.crateApiHealthGarminEndpointsFetchBodyBattery(
  client: client,
  rateLimiter: rateLimiter,
  from: from,
  to: to,
  isCn: isCn,
);

/// Fetch stress data for a date range.
Future<Value> fetchStress({
  required Client client,
  required GarminRateLimiter rateLimiter,
  required NaiveDate from,
  required NaiveDate to,
  required bool isCn,
}) => RustLib.instance.api.crateApiHealthGarminEndpointsFetchStress(
  client: client,
  rateLimiter: rateLimiter,
  from: from,
  to: to,
  isCn: isCn,
);

/// Fetch activities (paginated).
Future<Value> fetchActivities({
  required Client client,
  required GarminRateLimiter rateLimiter,
  required int start,
  required int limit,
  required bool isCn,
}) => RustLib.instance.api.crateApiHealthGarminEndpointsFetchActivities(
  client: client,
  rateLimiter: rateLimiter,
  start: start,
  limit: limit,
  isCn: isCn,
);

/// Fetch training status (includes VO2 max).
Future<Value> fetchTrainingStatus({
  required Client client,
  required GarminRateLimiter rateLimiter,
  required bool isCn,
}) => RustLib.instance.api.crateApiHealthGarminEndpointsFetchTrainingStatus(
  client: client,
  rateLimiter: rateLimiter,
  isCn: isCn,
);

/// Fetch weight data for a date.
Future<Value> fetchWeight({
  required Client client,
  required GarminRateLimiter rateLimiter,
  required NaiveDate date,
  required bool isCn,
}) => RustLib.instance.api.crateApiHealthGarminEndpointsFetchWeight(
  client: client,
  rateLimiter: rateLimiter,
  date: date,
  isCn: isCn,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Value>>
abstract class Value implements RustOpaqueInterface {}
