// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../../lib.dart';
import '../provider.dart';
import 'endpoints.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Map steps JSON to DailyMetric.
///
/// Garmin returns 15-minute interval arrays. We sum all intervals to
/// get the daily total.
Future<DailyMetric?> mapSteps({required Value json, required NaiveDate date}) =>
    RustLib.instance.api.crateApiHealthGarminMapperMapSteps(
      json: json,
      date: date,
    );

/// Map sleep JSON to SleepSession.
///
/// Garmin returns `{ "dailySleepDTO": { ... }, ... }`.
/// Key fields: `id` (epoch ms), `sleepStartTimestampGMT` (epoch ms),
/// `sleepTimeSeconds`, `deepSleepSeconds`, `lightSleepSeconds`,
/// `remSleepSeconds`, `awakeSleepSeconds`.
Future<SleepSession?> mapSleep({
  required Value json,
  required NaiveDate date,
}) => RustLib.instance.api.crateApiHealthGarminMapperMapSleep(
  json: json,
  date: date,
);

/// Map RHR JSON to DailyMetric.
///
/// Garmin returns `{ "allMetrics": { "metricsMap": { "WELLNESS_RESTING_HEART_RATE": [...] } } }`.
Future<DailyMetric?> mapRhr({required Value json, required NaiveDate date}) =>
    RustLib.instance.api.crateApiHealthGarminMapperMapRhr(
      json: json,
      date: date,
    );

/// Map HRV JSON to DailyMetric.
///
/// Garmin returns `{ "hrvSummary": { "lastNightAvg": 103, ... }, ... }`.
Future<DailyMetric?> mapHrv({required Value json, required NaiveDate date}) =>
    RustLib.instance.api.crateApiHealthGarminMapperMapHrv(
      json: json,
      date: date,
    );

/// Map heart rate from sleep or daily summary JSON.
///
/// From sleep DTO: `avgHeartRate` field.
Future<DailyMetric?> mapHeartRateFromSleep({
  required Value json,
  required NaiveDate date,
}) => RustLib.instance.api.crateApiHealthGarminMapperMapHeartRateFromSleep(
  json: json,
  date: date,
);

/// Map Body Battery JSON to BodyBatteryDay.
///
/// Garmin returns an array. Each entry has `date`, `charged`, `drained`,
/// and `bodyBatteryValuesArray` (per-slot readings).
Future<BodyBatteryDay?> mapBodyBattery({
  required Value json,
  required NaiveDate date,
}) => RustLib.instance.api.crateApiHealthGarminMapperMapBodyBattery(
  json: json,
  date: date,
);

/// Map stress JSON to DailyMetric.
///
/// Garmin returns `{ "avgStressLevel": 19, "maxStressLevel": 86, ... }`.
Future<DailyMetric?> mapStress({
  required Value json,
  required NaiveDate date,
}) => RustLib.instance.api.crateApiHealthGarminMapperMapStress(
  json: json,
  date: date,
);

/// Map activity JSON to ActivityRecord.
///
/// Garmin returns `{ "activityId": ..., "activityType": { "typeKey": "cycling" }, ... }`.
Future<ActivityRecord?> mapActivity({required Value json}) =>
    RustLib.instance.api.crateApiHealthGarminMapperMapActivity(json: json);

/// Map weight JSON to PointMetric.
///
/// Garmin returns `{ "dateWeightList": [...] }` or direct array.
Future<PointMetric?> mapWeight({
  required Value json,
  required NaiveDate date,
}) => RustLib.instance.api.crateApiHealthGarminMapperMapWeight(
  json: json,
  date: date,
);

/// Map VO2 max from training status JSON.
Future<DailyMetric?> mapVo2Max({
  required Value json,
  required NaiveDate date,
}) => RustLib.instance.api.crateApiHealthGarminMapperMapVo2Max(
  json: json,
  date: date,
);

/// Build a full HealthSnapshot from individual endpoint results.
Future<HealthSnapshot> buildSnapshot({
  required List<DailyMetric> steps,
  required List<SleepSession> sleepSessions,
  required List<DailyMetric> restingHr,
  required List<DailyMetric> hrv,
  required List<DailyMetric> heartRate,
  required List<BodyBatteryDay> bodyBattery,
  required List<DailyMetric> stress,
  required List<PointMetric> weight,
  required List<DailyMetric> vo2Max,
}) => RustLib.instance.api.crateApiHealthGarminMapperBuildSnapshot(
  steps: steps,
  sleepSessions: sleepSessions,
  restingHr: restingHr,
  hrv: hrv,
  heartRate: heartRate,
  bodyBattery: bodyBattery,
  stress: stress,
  weight: weight,
  vo2Max: vo2Max,
);
