// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `run`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GarminRateLimiter>>
abstract class GarminRateLimiter implements RustOpaqueInterface {
  /// Sleep for the 429 backoff duration.
  Future<void> backoffSleep();

  static Future<GarminRateLimiter> default_() => RustLib.instance.api
      .crateApiHealthGarminRateLimiterGarminRateLimiterDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<GarminRateLimiter> newInstance() => RustLib.instance.api
      .crateApiHealthGarminRateLimiterGarminRateLimiterNew();

  /// Call when a 429 is received. Returns the backoff duration.
  Future<Duration> on429();

  /// Call when a successful request is made. Resets 429 counter.
  Future<void> onSuccess();
}
