// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `clear`, `clear`, `load`, `load`, `save`, `save`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StoredSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTokenStore>>
abstract class InMemoryTokenStore implements RustOpaqueInterface, TokenStore {
  static Future<InMemoryTokenStore> default_() => RustLib.instance.api
      .crateApiHealthGarminTokenStoreInMemoryTokenStoreDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<InMemoryTokenStore> newInstance() => RustLib.instance.api
      .crateApiHealthGarminTokenStoreInMemoryTokenStoreNew();
}
