// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'provider.dart';

// These functions are ignored because they have generic arguments: `sync_activities`, `sync_daily_range`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < TokenStore >>>
abstract class ArcTokenStore implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GarminProvider>>
abstract class GarminProvider implements RustOpaqueInterface, HealthProvider {
  /// Get a reference to the underlying client (for auth operations).
  Future<void> client();

  Future<bool> isAuthenticated();

  Future<void> name();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new Garmin provider with the given token store.
  /// `is_cn` selects between China (connect.garmin.cn) and global
  /// (connect.garmin.com) endpoints.
  static Future<GarminProvider> newInstance({
    required ArcTokenStore tokenStore,
    required bool isCn,
  }) => RustLib.instance.api.crateApiHealthGarminGarminProviderNew(
    tokenStore: tokenStore,
    isCn: isCn,
  );
}
