// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `sync_activities`, `sync_daily_range`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BodyBatteryDay>>
abstract class BodyBatteryDay implements RustOpaqueInterface {
  int get charged;

  NaiveDate get date;

  int get drained;

  String get id;

  int get max;

  int get min;

  set charged(int charged);

  set date(NaiveDate date);

  set drained(int drained);

  set id(String id);

  set max(int max);

  set min(int min);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DailyMetric>>
abstract class DailyMetric implements RustOpaqueInterface {
  NaiveDate get date;

  String get id;

  String? get sourceDevice;

  String get unit;

  double get value;

  set date(NaiveDate date);

  set id(String id);

  set sourceDevice(String? sourceDevice);

  set unit(String unit);

  set value(double value);
}

abstract class HealthProvider {
  /// Check if the provider has valid credentials.
  Future<bool> isAuthenticated();

  /// Provider display name (e.g. "Garmin Connect").
  Future<void> name();
}

/// One workout/activity session.
class ActivityRecord {
  final String id;

  /// Lowercased activity type (e.g. "running", "cycling").
  final String activityType;

  /// ISO 8601 UTC timestamp.
  final String startedAt;
  final int durationSeconds;
  final double? totalEnergyKcal;
  final double? totalDistanceMeters;
  final String? sourceDevice;

  const ActivityRecord({
    required this.id,
    required this.activityType,
    required this.startedAt,
    required this.durationSeconds,
    this.totalEnergyKcal,
    this.totalDistanceMeters,
    this.sourceDevice,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      activityType.hashCode ^
      startedAt.hashCode ^
      durationSeconds.hashCode ^
      totalEnergyKcal.hashCode ^
      totalDistanceMeters.hashCode ^
      sourceDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActivityRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          activityType == other.activityType &&
          startedAt == other.startedAt &&
          durationSeconds == other.durationSeconds &&
          totalEnergyKcal == other.totalEnergyKcal &&
          totalDistanceMeters == other.totalDistanceMeters &&
          sourceDevice == other.sourceDevice;
}

/// Normalized daily health snapshot — provider-agnostic.
class HealthSnapshot {
  final List<DailyMetric> steps;
  final List<SleepSession> sleepSessions;
  final List<DailyMetric> restingHr;
  final List<DailyMetric> hrv;
  final List<DailyMetric> heartRate;
  final List<DailyMetric> activeEnergy;
  final List<DailyMetric> vo2Max;
  final List<PointMetric> weight;
  final List<PointMetric> bodyFat;
  final List<DailyMetric> floorsClimbed;
  final List<DailyMetric> respiratoryRate;

  /// Garmin-specific: Body Battery daily summary.
  /// Stored in `payload_json` on the Dart side.
  final List<BodyBatteryDay> bodyBattery;

  /// Garmin-specific: daily stress average.
  final List<DailyMetric> stress;

  const HealthSnapshot({
    required this.steps,
    required this.sleepSessions,
    required this.restingHr,
    required this.hrv,
    required this.heartRate,
    required this.activeEnergy,
    required this.vo2Max,
    required this.weight,
    required this.bodyFat,
    required this.floorsClimbed,
    required this.respiratoryRate,
    required this.bodyBattery,
    required this.stress,
  });

  static Future<HealthSnapshot> default_() =>
      RustLib.instance.api.crateApiHealthProviderHealthSnapshotDefault();

  @override
  int get hashCode =>
      steps.hashCode ^
      sleepSessions.hashCode ^
      restingHr.hashCode ^
      hrv.hashCode ^
      heartRate.hashCode ^
      activeEnergy.hashCode ^
      vo2Max.hashCode ^
      weight.hashCode ^
      bodyFat.hashCode ^
      floorsClimbed.hashCode ^
      respiratoryRate.hashCode ^
      bodyBattery.hashCode ^
      stress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthSnapshot &&
          runtimeType == other.runtimeType &&
          steps == other.steps &&
          sleepSessions == other.sleepSessions &&
          restingHr == other.restingHr &&
          hrv == other.hrv &&
          heartRate == other.heartRate &&
          activeEnergy == other.activeEnergy &&
          vo2Max == other.vo2Max &&
          weight == other.weight &&
          bodyFat == other.bodyFat &&
          floorsClimbed == other.floorsClimbed &&
          respiratoryRate == other.respiratoryRate &&
          bodyBattery == other.bodyBattery &&
          stress == other.stress;
}

/// A single timestamped measurement (weight, body fat, etc.).
class PointMetric {
  final String id;

  /// ISO 8601 UTC timestamp.
  final String measuredAt;
  final double value;
  final String unit;
  final String? sourceDevice;

  const PointMetric({
    required this.id,
    required this.measuredAt,
    required this.value,
    required this.unit,
    this.sourceDevice,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      measuredAt.hashCode ^
      value.hashCode ^
      unit.hashCode ^
      sourceDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PointMetric &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          measuredAt == other.measuredAt &&
          value == other.value &&
          unit == other.unit &&
          sourceDevice == other.sourceDevice;
}

/// One sleep session that has already ended.
class SleepSession {
  final String id;

  /// ISO 8601 UTC timestamp.
  final String startedAt;

  /// Total asleep duration in seconds.
  final int durationSeconds;
  final String? sourceDevice;

  /// Optional per-stage histogram JSON.
  final String? stageHistogramJson;

  const SleepSession({
    required this.id,
    required this.startedAt,
    required this.durationSeconds,
    this.sourceDevice,
    this.stageHistogramJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      startedAt.hashCode ^
      durationSeconds.hashCode ^
      sourceDevice.hashCode ^
      stageHistogramJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SleepSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          startedAt == other.startedAt &&
          durationSeconds == other.durationSeconds &&
          sourceDevice == other.sourceDevice &&
          stageHistogramJson == other.stageHistogramJson;
}
