// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HealthSyncEngine>>
abstract class HealthSyncEngine implements RustOpaqueInterface {
  /// Register a provider.
  Future<void> addProvider({required ArcHealthProvider provider});

  /// Get current cursors.
  Future<Map<String, NaiveDate>> cursors();

  static Future<HealthSyncEngine> default_() =>
      RustLib.instance.api.crateApiHealthSyncEngineHealthSyncEngineDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<HealthSyncEngine> newInstance() =>
      RustLib.instance.api.crateApiHealthSyncEngineHealthSyncEngineNew();

  /// Set a cursor (for restoring from persistence).
  Future<void> setCursor({required String provider, required NaiveDate date});

  /// Sync a single provider, using the cursor to avoid re-fetching.
  Future<SyncOutcome> syncProvider({
    required String providerName,
    required NaiveDate from,
    required NaiveDate to,
  });

  /// Sync all providers for the given range.
  Future<List<SyncOutcome>> syncRange({
    required NaiveDate from,
    required NaiveDate to,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncOutcome>>
abstract class SyncOutcome implements RustOpaqueInterface {
  BigInt get activitiesCount;

  BigInt get durationMs;

  List<String> get errors;

  NaiveDate get from;

  BigInt get metricsCount;

  String get provider;

  NaiveDate get to;

  set activitiesCount(BigInt activitiesCount);

  set durationMs(BigInt durationMs);

  set errors(List<String> errors);

  set from(NaiveDate from);

  set metricsCount(BigInt metricsCount);

  set provider(String provider);

  set to(NaiveDate to);
}
