// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `normalize_json`, `parse_requested_tool_call`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CatalogSummary`, `RequestedToolCall`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

Future<String> agentRuntimeProtocolVersion() =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeProtocolVersion();

Future<String> agentRuntimeCatalogVersion() =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeCatalogVersion();

Future<String> agentRuntimeCatalogSummary({required String catalogJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeCatalogSummary(
      catalogJson: catalogJson,
    );

Future<String> agentRuntimeValidateRunRequest({required String requestJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeValidateRunRequest(
      requestJson: requestJson,
    );

Future<String> agentRuntimeValidateTrace({required String traceJson}) => RustLib
    .instance
    .api
    .crateApiAgentRuntimeAgentRuntimeValidateTrace(traceJson: traceJson);

Future<String> agentRuntimeValidateToolSpec({required String toolJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeValidateToolSpec(
      toolJson: toolJson,
    );

Future<String> agentRuntimeValidateLlmRequest({required String requestJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeValidateLlmRequest(
      requestJson: requestJson,
    );

Future<String> agentRuntimeValidateLlmResponse({
  required String responseJson,
}) => RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeValidateLlmResponse(
  responseJson: responseJson,
);

Future<String> agentRuntimeCompleteMockLlm({
  required String requestJson,
  required String responseText,
}) => RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeCompleteMockLlm(
  requestJson: requestJson,
  responseText: responseText,
);

Future<String> agentRuntimeStartRunStep({
  required String catalogJson,
  required String requestJson,
  required String agentId,
}) => RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeStartRunStep(
  catalogJson: catalogJson,
  requestJson: requestJson,
  agentId: agentId,
);

Future<String> agentRuntimeContinueRunStep({
  required String catalogJson,
  required String previousStepJson,
  required String toolResponseJson,
  required String agentId,
}) => RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeContinueRunStep(
  catalogJson: catalogJson,
  previousStepJson: previousStepJson,
  toolResponseJson: toolResponseJson,
  agentId: agentId,
);
