// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> agentRuntimeProtocolVersion() =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeProtocolVersion();

Future<String> agentRuntimeCatalogVersion() =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeCatalogVersion();

Future<String> agentRuntimeCatalogSummary({required String catalogJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeCatalogSummary(
      catalogJson: catalogJson,
    );

Future<String> agentRuntimeValidateRunRequest({required String requestJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeValidateRunRequest(
      requestJson: requestJson,
    );

Future<String> agentRuntimeValidateTrace({required String traceJson}) => RustLib
    .instance
    .api
    .crateApiAgentRuntimeAgentRuntimeValidateTrace(traceJson: traceJson);

Future<String> agentRuntimeValidateToolSpec({required String toolJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeValidateToolSpec(
      toolJson: toolJson,
    );

Future<String> agentRuntimeValidateLlmRequest({required String requestJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeValidateLlmRequest(
      requestJson: requestJson,
    );

Future<String> agentRuntimeValidateLlmResponse({
  required String responseJson,
}) => RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeValidateLlmResponse(
  responseJson: responseJson,
);

Future<String> agentRuntimeValidateChatTurnRequest({
  required String requestJson,
}) => RustLib.instance.api
    .crateApiAgentRuntimeAgentRuntimeValidateChatTurnRequest(
      requestJson: requestJson,
    );

Future<String> agentRuntimeCompleteMockLlm({
  required String requestJson,
  required String responseText,
}) => RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeCompleteMockLlm(
  requestJson: requestJson,
  responseText: responseText,
);

Future<String> agentRuntimeCompleteProfileLlm({required String requestJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeCompleteProfileLlm(
      requestJson: requestJson,
    );

Stream<String> agentRuntimeStreamMockLlm({
  required String requestJson,
  required String responseText,
}) => RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeStreamMockLlm(
  requestJson: requestJson,
  responseText: responseText,
);

Stream<String> agentRuntimeStreamProfileLlm({required String requestJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeStreamProfileLlm(
      requestJson: requestJson,
    );

Stream<String> agentRuntimeStreamChatTurn({required String requestJson}) =>
    RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeStreamChatTurn(
      requestJson: requestJson,
    );

Future<String> agentRuntimeStartProfileTurnSnapshot({
  required String catalogJson,
  required String llmRequestJson,
  required String agentId,
  required String runMetadataJson,
  required int maxEffectSteps,
  required int maxSubagentDepth,
}) => RustLib.instance.api
    .crateApiAgentRuntimeAgentRuntimeStartProfileTurnSnapshot(
      catalogJson: catalogJson,
      llmRequestJson: llmRequestJson,
      agentId: agentId,
      runMetadataJson: runMetadataJson,
      maxEffectSteps: maxEffectSteps,
      maxSubagentDepth: maxSubagentDepth,
    );

Future<String> agentRuntimeStartRunSnapshot({
  required String catalogJson,
  required String requestJson,
  required String agentId,
  required int maxEffectSteps,
  required int maxSubagentDepth,
}) => RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeStartRunSnapshot(
  catalogJson: catalogJson,
  requestJson: requestJson,
  agentId: agentId,
  maxEffectSteps: maxEffectSteps,
  maxSubagentDepth: maxSubagentDepth,
);

Future<String> agentRuntimeContinueRunSnapshot({
  required String catalogJson,
  required String snapshotJson,
  required String effectResponseJson,
  required String agentId,
}) => RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeContinueRunSnapshot(
  catalogJson: catalogJson,
  snapshotJson: snapshotJson,
  effectResponseJson: effectResponseJson,
  agentId: agentId,
);

Future<String> agentRuntimeCancelRunSnapshot({
  required String catalogJson,
  required String snapshotJson,
  required String agentId,
  required String reason,
}) => RustLib.instance.api.crateApiAgentRuntimeAgentRuntimeCancelRunSnapshot(
  catalogJson: catalogJson,
  snapshotJson: snapshotJson,
  agentId: agentId,
  reason: reason,
);

Future<String> agentRuntimeStartRequestedSubagentSnapshot({
  required String catalogJson,
  required String parentSnapshotJson,
}) => RustLib.instance.api
    .crateApiAgentRuntimeAgentRuntimeStartRequestedSubagentSnapshot(
      catalogJson: catalogJson,
      parentSnapshotJson: parentSnapshotJson,
    );

Future<String> agentRuntimeResumeParentFromSubagentSnapshot({
  required String catalogJson,
  required String parentSnapshotJson,
  required String childSnapshotJson,
}) => RustLib.instance.api
    .crateApiAgentRuntimeAgentRuntimeResumeParentFromSubagentSnapshot(
      catalogJson: catalogJson,
      parentSnapshotJson: parentSnapshotJson,
      childSnapshotJson: childSnapshotJson,
    );
