// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pick_onnx_path`, `read_required`

int embeddingDim() => RustLib.instance.api.crateApiEmbedderEmbeddingDim();

String embedderFingerprint() =>
    RustLib.instance.api.crateApiEmbedderEmbedderFingerprint();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GemmaEmbedder>>
abstract class GemmaEmbedder implements RustOpaqueInterface {
  /// Output dimension. Always 768 for EmbeddingGemma-300M; the
  /// `#[frb(sync)]` hint makes this a plain `int` getter on Dart.
  int dimension();

  /// Embed `text` into a unit-length 768-d vector. fastembed
  /// L2-normalises by default; we sanity-check the dimension to
  /// catch model/config mismatches early.
  Future<Float32List> embed({required String text});

  /// Stable identifier. The Memory Layer persists this with every
  /// embedding so swapping models invalidates the vectors.
  String fingerprint();

  /// Load the embedder from `model_dir`. Slow (~seconds for ONNX
  /// session warm-up); FRB makes this `Future<GemmaEmbedder>` on
  /// the Dart side automatically.
  ///
  /// `ort_dylib_path` points at `libonnxruntime.{dylib,so,dll}` —
  /// we use the `ort-load-dynamic` flavour to avoid the duplicate
  /// `.o` files that ORT's prebuilt static archives contain (which
  /// would surface as ~756 "duplicate symbol" linker errors when
  /// force-loaded into the Flutter app). Pass an empty string to
  /// fall back to whatever `ORT_DYLIB_PATH` env var is already
  /// set in the process (useful for tests).
  static Future<GemmaEmbedder> load({
    required String modelDir,
    required String ortDylibPath,
  }) => RustLib.instance.api.crateApiEmbedderGemmaEmbedderLoad(
    modelDir: modelDir,
    ortDylibPath: ortDylibPath,
  );
}
