// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the Garmin client. Returns auth state as JSON.
Future<String> garminInit({String? storedTokenJson, required bool isCn}) =>
    RustLib.instance.api.crateApiHealthGarminInit(
      storedTokenJson: storedTokenJson,
      isCn: isCn,
    );

/// Authenticate with Garmin Connect. Returns JSON.
Future<String> garminAuthenticate({
  required String email,
  required String password,
}) => RustLib.instance.api.crateApiHealthGarminAuthenticate(
  email: email,
  password: password,
);

/// Submit MFA code. Returns JSON.
Future<String> garminSubmitMfa({required String code}) =>
    RustLib.instance.api.crateApiHealthGarminSubmitMfa(code: code);

/// Get current auth state as JSON.
Future<String> garminAuthState() =>
    RustLib.instance.api.crateApiHealthGarminAuthState();

/// Sync health data for a date range. Returns SyncOutcome JSON.
Future<String> garminSyncRange({required String from, required String to}) =>
    RustLib.instance.api.crateApiHealthGarminSyncRange(from: from, to: to);

/// Sync health data for a date range with streaming progress events.
///
/// Emits [GarminSyncProgress] events via [StreamSink] as each day and
/// the activities fetch complete. The stream closes when the sync is
/// done or cancelled.
Stream<GarminSyncProgress> garminSyncRangeStream({
  required String from,
  required String to,
}) => RustLib.instance.api.crateApiHealthGarminSyncRangeStream(
  from: from,
  to: to,
);

/// Cancel an in-progress sync. The running sync will stop after the
/// current day finishes.
Future<void> garminSyncCancel() =>
    RustLib.instance.api.crateApiHealthGarminSyncCancel();

/// Get sync cursors as JSON.
Future<String> garminSyncCursors() =>
    RustLib.instance.api.crateApiHealthGarminSyncCursors();

/// Logout and clear stored credentials.
Future<void> garminLogout() =>
    RustLib.instance.api.crateApiHealthGarminLogout();

/// Export the current session as JSON for Dart-side persistence.
///
/// Returns the StoredSession JSON if authenticated, or null.
Future<String?> garminExportSession() =>
    RustLib.instance.api.crateApiHealthGarminExportSession();

/// Progress event emitted during Garmin sync (only primitive fields for FRB).
class GarminSyncProgress {
  /// Phase: "days" | "activities" | "snapshot" | "done"
  final String phase;

  /// Current index (day offset or activity offset).
  final int current;

  /// Total count (days or activities).
  final int total;

  /// Running total of metrics fetched so far.
  final int metricsCount;

  /// Accumulated error messages.
  final List<String> errors;

  /// HealthSnapshot JSON — only set on the "snapshot" phase event.
  /// Null/empty on all other phases.
  final String? snapshotJson;

  const GarminSyncProgress({
    required this.phase,
    required this.current,
    required this.total,
    required this.metricsCount,
    required this.errors,
    this.snapshotJson,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      current.hashCode ^
      total.hashCode ^
      metricsCount.hashCode ^
      errors.hashCode ^
      snapshotJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GarminSyncProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          current == other.current &&
          total == other.total &&
          metricsCount == other.metricsCount &&
          errors == other.errors &&
          snapshotJson == other.snapshotJson;
}
