// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the Garmin client. Returns auth state as JSON.
Future<String> garminInit({String? storedTokenJson, required bool isCn}) =>
    RustLib.instance.api.crateApiHealthGarminInit(
      storedTokenJson: storedTokenJson,
      isCn: isCn,
    );

/// Authenticate with Garmin Connect. Returns JSON.
Future<String> garminAuthenticate({
  required String email,
  required String password,
}) => RustLib.instance.api.crateApiHealthGarminAuthenticate(
  email: email,
  password: password,
);

/// Submit MFA code. Returns JSON.
Future<String> garminSubmitMfa({required String code}) =>
    RustLib.instance.api.crateApiHealthGarminSubmitMfa(code: code);

/// Get current auth state as JSON.
Future<String> garminAuthState() =>
    RustLib.instance.api.crateApiHealthGarminAuthState();

/// Sync health data for a date range. Returns SyncOutcome JSON.
Future<String> garminSyncRange({required String from, required String to}) =>
    RustLib.instance.api.crateApiHealthGarminSyncRange(from: from, to: to);

/// Get sync cursors as JSON.
Future<String> garminSyncCursors() =>
    RustLib.instance.api.crateApiHealthGarminSyncCursors();

/// Logout and clear stored credentials.
Future<void> garminLogout() =>
    RustLib.instance.api.crateApiHealthGarminLogout();

/// Export the current session as JSON for Dart-side persistence.
///
/// Returns the StoredSession JSON if authenticated, or null.
Future<String?> garminExportSession() =>
    RustLib.instance.api.crateApiHealthGarminExportSession();
