// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> marketRequest({
  required String requestId,
  required String requestJson,
}) => RustLib.instance.api.crateApiMarketMarketRequest(
  requestId: requestId,
  requestJson: requestJson,
);

Future<void> marketCancel({required String requestId}) =>
    RustLib.instance.api.crateApiMarketMarketCancel(requestId: requestId);
